### ISSUE TITLE
Javascript Errors Being Thrown. 

### ISSUE THREAD

**Issue by brideo** [zipMoney/magento2#57]
Hey, I'm seeing javascript pages for various users 
```
TypeError: undefined is not an object (evaluating 'this.data[this.DATA_ASSETS_KEY]')
  at value(/lib/js/zm-widget-js/dist/zip-widget.min.js:2:55850)
  at ? (/lib/js/zm-widget-js/modules/marketing.bundle.afceec3743278671dd92.js:2:8993)
  at n(/lib/js/zm-widget-js/dist/zip-widget.min.js:2:14228)
  at ? (/lib/js/zm-widget-js/dist/zip-widget.min.js:2:15320)
  at ? (/lib/js/zm-widget-js/dist/zip-widget.min.js:2:9023)
  at initializePromise([native code])
  at Promise([native code])
  at r(/lib/js/zm-widget-js/dist/zip-widget.min.js:2:8815)
  at n(/lib/js/zm-widget-js/dist/zip-widget.min.js:2:14228)
  at ? (/lib/js/zm-widget-js/dist/zip-widget.min.js:2:15320)
  at a(/lib/js/zm-widget-js/dist/zip-widget.min.js:2:8856)
  at promiseReactionJob([native code])
```

looks to be mainly iPhone Safari uses:

```
Mobile Safari12
Mobile Safari UI/WKWebView1
```

https://sentry.io/share/issue/5d9c4ab999e54fc19d655b49baf7b647/

**Comment by benzhangzip** [comment]
Hi @brideo,
The error you are getting is not related to this repo, it is our other releases on marketing asset widget JS library. We just recently launched the stable version of the new widget JS to support fast dynamic merchant specific JS lib to help customised your zip pay logo position on your website, you could using purely javascript configuration without HTML and using CSS selector to put the widget in any location before or after page load to fit any customisation.
The error you see is related to our old widget using webpack to spilt functionality to multiple small JS files that might have conflict on dynamic loading but now all merged to be one and this issue should be fixed. please let us know if still not working, we need to know the browser version and widget js you are using. 
Thanks.

**Comment by benzhangzip** [comment]
Close issue, it should be fixed already.
